apiVersion: v1
kind: Pod
metadata:
  name: bench
spec:
  containers:
  - name: bench
    image: ubuntu
    volumeMounts:
    - name: bench-pv-storage
      mountPath: /data
    resources:
      limits:
        cpu: 8
        memory: 16Gi
    command:
    - tail
    - -f
    - /dev/null
  nodeName: harvester-fzzb4
  volumes:
    - name: bench-pv-storage
      persistentVolumeClaim:
        claimName: bench-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bench-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn